--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPRING_PROJECT_HARDWARE
--------------------------------------------------------

  CREATE TABLE "JINWOO26"."SPRING_PROJECT_HARDWARE" 
   (	"H_NO" NUMBER(5,0), 
	"H_SUBJECT" VARCHAR2(50 BYTE), 
	"H_NAME" VARCHAR2(20 BYTE), 
	"H_CODE" VARCHAR2(20 BYTE), 
	"H_COUNT" NUMBER(5,0), 
	"H_CONTENT" VARCHAR2(500 BYTE), 
	"H_ID" VARCHAR2(20 BYTE), 
	"H_PRICE" VARCHAR2(20 BYTE), 
	"H_SCORE" VARCHAR2(5 BYTE), 
	"H_SUGGEST" NUMBER(5,0), 
	"H_TIME" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JINWOO26.SPRING_PROJECT_HARDWARE
SET DEFINE OFF;
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (9,'Test2','Root','POWER',8,'테스트값
테스트값
테스트값','test00','10000원','4점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (4,'2060Super','Rluan','GRAPHICCARD',3,'테스트','test00','800000원','3점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (5,'PC4-25600','ITS','RAM',1,'테스트','test00','30000원','5점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (6,'기가바이트 SSD','bears','SSD',9,'SSD','test00','200000원','5점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (7,'ST4000DM004','yuhan','HDD',4,'테스트','test11','300000원','3점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (8,'12900K','home','CPU',9,'테스트용값','test11','800000원','5점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (11,'1','1','CPU',0,'1','test00','1','1',0,to_date('21/12/14','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (3,'sysonic gold','lost_spirit','POWER',5,'테스트','test00','300000원','3점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (1,'3600X','yuhan3','CPU',12,'가성비 좋음33','test00','400000원','5점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (2,'B450','root','MAINBOARD',1,'test','test00','300000원','5점',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (12,'2','2','GRAPHICCARD',0,'2','test00','2','2',0,to_date('21/12/14','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_HARDWARE (H_NO,H_SUBJECT,H_NAME,H_CODE,H_COUNT,H_CONTENT,H_ID,H_PRICE,H_SCORE,H_SUGGEST,H_TIME) values (13,'45','55','RAM',0,'55','test00','55','55',0,to_date('21/12/14','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C0027180
--------------------------------------------------------

  CREATE UNIQUE INDEX "JINWOO26"."SYS_C0027180" ON "JINWOO26"."SPRING_PROJECT_HARDWARE" ("H_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SPRING_PROJECT_HARDWARE
--------------------------------------------------------

  ALTER TABLE "JINWOO26"."SPRING_PROJECT_HARDWARE" ADD PRIMARY KEY ("H_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
