--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPRING_PROJECT_USER
--------------------------------------------------------

  CREATE TABLE "JINWOO26"."SPRING_PROJECT_USER" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JINWOO26.SPRING_PROJECT_USER
SET DEFINE OFF;
Insert into JINWOO26.SPRING_PROJECT_USER (USER_ID,USER_PWD,USER_NAME,USER_EMAIL,USER_PHONE) values ('test11','11','test11','test11@naver.com','010-1112-2222');
Insert into JINWOO26.SPRING_PROJECT_USER (USER_ID,USER_PWD,USER_NAME,USER_EMAIL,USER_PHONE) values ('test00','00','test00','test2@naver.com','010-0000-0000');
--------------------------------------------------------
--  DDL for Index SYS_C0027174
--------------------------------------------------------

  CREATE UNIQUE INDEX "JINWOO26"."SYS_C0027174" ON "JINWOO26"."SPRING_PROJECT_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SPRING_PROJECT_USER
--------------------------------------------------------

  ALTER TABLE "JINWOO26"."SPRING_PROJECT_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
