--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPRING_PROJECT_SOFTWARE
--------------------------------------------------------

  CREATE TABLE "JINWOO26"."SPRING_PROJECT_SOFTWARE" 
   (	"S_NO" NUMBER(5,0), 
	"S_SUBJECT" VARCHAR2(50 BYTE), 
	"S_NAME" VARCHAR2(20 BYTE), 
	"S_CODE" VARCHAR2(20 BYTE), 
	"S_COUNT" NUMBER(5,0), 
	"S_CONTENT" VARCHAR2(500 BYTE), 
	"S_ID" VARCHAR2(20 BYTE), 
	"S_PRICE" VARCHAR2(20 BYTE), 
	"S_SCORE" VARCHAR2(5 BYTE), 
	"S_SUGGEST" NUMBER(5,0), 
	"S_TIME" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JINWOO26.SPRING_PROJECT_SOFTWARE
SET DEFINE OFF;
Insert into JINWOO26.SPRING_PROJECT_SOFTWARE (S_NO,S_SUBJECT,S_NAME,S_CODE,S_COUNT,S_CONTENT,S_ID,S_PRICE,S_SCORE,S_SUGGEST,S_TIME) values (2,'tt2','tt','WEB',30,'tt','test00','tt','tt',0,to_date('21/12/13','RR/MM/DD'));
Insert into JINWOO26.SPRING_PROJECT_SOFTWARE (S_NO,S_SUBJECT,S_NAME,S_CODE,S_COUNT,S_CONTENT,S_ID,S_PRICE,S_SCORE,S_SUGGEST,S_TIME) values (3,'test','test','MEDIA',1,'test','test11','test','test',0,to_date('21/12/13','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C0027203
--------------------------------------------------------

  CREATE UNIQUE INDEX "JINWOO26"."SYS_C0027203" ON "JINWOO26"."SPRING_PROJECT_SOFTWARE" ("S_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SPRING_PROJECT_SOFTWARE
--------------------------------------------------------

  ALTER TABLE "JINWOO26"."SPRING_PROJECT_SOFTWARE" ADD PRIMARY KEY ("S_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
